import validator from "validator";
import bcrypt from "bcrypt";
import jwt from "jsonwebtoken";
import userModel from "../models/userModel.js";

const createToken = (id) => {
  return jwt.sign({ id }, process.env.JWT_SECRET);
};

//Route for user logic
const loginUser = async (req, res) => {
  try {
    const { email, password } = req.body;
    const user = await userModel.findOne({ email });
    if (!user) {
      return res.json({ success: false, message: "User doesn't exist" });
    }

    const isMatch = await bcrypt.compare(password, user.password);

    if (isMatch) {
      const token = createToken(user._id);
      res.json({ success: true, token });
    } else {
      res.json({ success: false, message: "Invalid credentials" });
    }
  } catch (error) {
    console.log(error);
    res.json({ success: false, message: error.message });
  }
};

//Route for user registration
const registerUser = async (req, res) => {
  try {
    const { name, email, password } = req.body;

    //checking user already exist or not
    const exists = await userModel.findOne({ email });
    if (exists) {
      return res.json({ success: false, message: "User already exists" });
    }

    // validating email and strong password

    if (!validator.isEmail(email)) {
      return res.json({
        success: false,
        message: "Please enter a valid email",
      });
    }
    if (password.length < 8) {
      return res.json({
        success: false,
        message: "Please enter a strong password",
      });
    }

    //hashing user password
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(password, salt);

    const newUser = new userModel({
      name,
      email,
      password: hashedPassword,
    });

    const user = await newUser.save();

    const token = createToken(user._id);

    res.json({ success: true, token });
  } catch (error) {
    console.log(error);
    res.json({ success: false, message: error.message });
  }
};

//Route for admin login
const adminLogin = async (req, res) => {};

export { loginUser, registerUser, adminLogin };

/*{jwt is used to create token for user authentication and authorization. jwt is json web token.it is more more of accountability than secrecy.we have three main parts in jwt header.payload.signature. header contains the type of token and signing algorithm.payload contains the claims. claims are statements about an entity (typically, the user) and additional data. signature is used to verify that the sender of the jwt is who it says it is and to ensure that the message wasn't changed along the way.but what makes jwt really powerful is that it is self-contained. it means that all the information needed to verify the token is contained within the token itself. so we don't need to query the database to verify the token. this makes jwt very fast and efficient.but for header what type of sigining algorithm we use in this project is HS256 (hmac with sha-256). it is a symmetric algorithm which means that the same secret key is used for both signing and verification. so we need to keep the secret key safe and secure.How to explicitly specify the algorithm while creating jwt token?can be explicit:

jwt.sign(
  { id },
  process.env.JWT_SECRET,
  { algorithm: "HS256", expiresIn: "1d" }
);
In this code, the signing algorithm is HS256 because a single secret key is used and no algorithm is specified, so the jsonwebtoken library defaults to HMAC-SHA256.
so header part contains predefined fields like typ (type of token) and alg (signing algorithm).typ is always JWT and alg is the algorithm used to sign the token.The JWT header contains predefined fields such as typ and alg. While these fields are generated automatically by the JWT library, their values are determined by the server’s signing configuration, not by the user. The header is protected by the signature and cannot be safely altered.
Header is NOT user input (security point)

This is very important:

The client/user never sends or chooses the header

The header is:

Generated by the JWT library

Based on server configuration
In JWT, the payload contains claims that describe the identity and attributes of the token’s subject, while verification of those claims is ensured by the token’s signature and used by the server to decide whether the requested action is allowed.so here jwt.sign({id},process.env.JWT_SECRET) id belongs to payload part of jwt token.process.env.JWT_SECRET belongs to signature part of jwt token.but sginature is formed by combining encoded header, encoded payload, and secret key using the specified algorithm.so the JWT_SECRET is not part of the token itself but is used to create the signature that secures the token. 
Header → how it’s signed

Payload → what it claims

Secret → signing authority

Signature → proof of authenticity

//bcrypt is used to hash password before storing it in database. hashing is a one-way function that converts plain text password into a fixed-length string of characters. even if two users have same password, their hashed passwords will be different because of salting. salting is the process of adding random data to the password before hashing it.The salt is not added to the password; it is used by the hashing algorithm.bcrypt cannot retrieve the original password because hashing is a one-way function where the salt influences the transformation, not something appended that can be removed.

when we send login multiple times for single user with same password, we will get diffrent hashed password and token each time because of salting and jwt token generation process. 


*/
